### PR TITLE
Update Parse version to 1.3.0.1.

### LINKED ISSUE #18: Update Parse dependency to 1.3.0
Current version of Parse is 1.3.0.

http://cocoapods.org/?q=parse

### PR DESCRIPTION
**Pull request by hokster7**
Update Parse dependency. I didn't run the test suite. @kastiglione you probably have the environment set up already. Fixes #18.

### CODE REVIEW

**Comment by kastiglione** [comment]
Looks good. I don't have a CP setup, so I'll just accept this as is.

I haven't kept up, should the podspec be converted to json?

**Comment by hokster7** [comment]
Wow. What? JSON podspecs? I am not the person to ask :P

**Comment by robb** [comment]
AFAIK, only podspecs submitted to trunk need to be JSON and will be converted by `pod trunk push`

**Comment by kastiglione** [comment]
Thanks @robb.

**Pull request merged**
